cmd_name="init"
cmd_help_msg="Create a new LaTeX Environment."

cmd_run() {
  local target_dir="${1:-.}" 

  if [ ! -d "$target_dir" ]; then
    mkdir -p "$target_dir" || {
      log_error "Failed to create directory: $target_dir"
      log_info "Exiting.."
      exit 1
    }
  fi

  if [ -d "$target_dir" ] && [ "$(ls -A "$target_dir")" ]; then
    log_error "Directory '$target_dir' must be empty."
    log_info "Project was not created."
    log_info "Exiting.."
    exit 0
  fi

  log_info "Initializing project at: $target_dir"

  cd "$target_dir"

  mkdir -p "$DOC_DIR"
  mkdir -p "$FIG_DIR"
  mkdir -p "$INC_DIR"
  mkdir -p "$BUILD_DIR"
  mkdir -p "$PKG_DIR"
  mkdir -p "$TEXMF_DIR"
  mkdir -p "$TPL_DIR"

  touch ".gitignore"
  cat <<EOF > ".gitignore"
.idea
.vscode
out/
ltxe/
EOF

  touch "$LOCK_FILE"
  cat <<EOF > "$LOCK_FILE"
# DO NOT EDIT THIS FILE.
EOF

  touch "$TPL_DIR/default.tex"
  cat <<EOF > "$TPL_DIR/default.tex"
\documentclass{article}

\begin{document}
  % Edit this template to use it with the 'ltxe new' command.
\end{document}
EOF

  local script_path="$(realpath "$0")"
  cp "$script_path" "$SCRIPT_FILE"

  log_info "Project created at: $target_dir"
}
